spring.datasource.url= jdbc:postgresql://localhost:5432/TG_InfoBot
spring.datasource.username= userBot
spring.datasource.password= user-bot-1025
telegram.bot.token=
telegram.bot.name= My_Info_Bot

server.port = 8080

# Hibernate ddl auto (create, create-drop, validate, update, none)
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql= true

spring.jpa.properties.hibernate.format_sql= true

spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

logging.level.pro.sky.telegrambot= DEBUG

spring.liquibase.change-log= classpath:liquibase/changelog-master.yml
logging.level.liquibase= DEBUG